#require_relative 'seeds/users'
#require_relative 'seeds/novels'
# require_relative 'seeds/genres'
#require_relative 'seeds/chapters'
# require_relative 'seeds/genres_novels'
require_relative 'seeds/liked_novels'
